apiVersion: apps/v1
kind: Deployment
metadata:
  name: devsolutions-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devsolutions-backend
  template:
    metadata:
      labels:
        app: devsolutions-backend
    spec:
      containers:
      - name: backend
        image: devsolutions-backend:v1
        ports:
        - containerPort: 5000
        env:
        - name: DB_HOST
          value: "devsolutions-db"
        - name: DB_PORT
          value: "3306"
        - name: DB_NAME
          value: "devdb"
        - name: DB_USER
          value: "root"
        - name: DB_PASSWORD
          value: "rootpassword"

---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  type: NodePort
  selector:
    app: devsolutions-backend
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30002
