apiVersion: apps/v1
kind: Deployment
metadata:
  name: devsolutions-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devsolutions-app
  template:
    metadata:
      labels:
        app: devsolutions-app
    spec:
      containers:
      - name: devsolutions-app
        image: devsolutions-app:v1
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: devsolutions-app-service
spec:
  type: NodePort
  selector:
    app: devsolutions-app
  ports:
    - protocol: TCP
      port: 80
      nodePort: 30001
